sonar.projectKey=weilim0513-tech_pace-server
sonar.organization=weilim0513-tech

# 소스 및 테스트 경로
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main

# JaCoCo 커버리지
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

# 인코딩
sonar.sourceEncoding=UTF-8

# 제외 패턴 (설정/엔티티/메인클래스는 커버리지 제외)
sonar.exclusions=**/config/**,**/entity/**,**/*Application*,**/dto/**

# 중복 코드 제외
sonar.cpd.exclusions=**/entity/**,**/dto/**
